package com.rms.restaurant_management_system.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    BUSINESS_RULE_VIOLATION,
    AUTHENTICATION_REQUIRED,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    SESSION_REJECTED,
    ACCOUNT_LOCKED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    RESOURCE_CONFLICT,
    CONCURRENT_UPDATE,
    RESERVATION_CONFLICT,
    PAYMENT_ALREADY_PROCESSED,
    INVALID_ORDER_STATE,
    RATE_LIMIT_EXCEEDED,
    EXTERNAL_SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
