package com.restaurant.service;
import com.restaurant.dto.auth.*; import com.restaurant.entity.*; import com.restaurant.exception.*; import com.restaurant.model.UserStatus; import com.restaurant.repository.*; import com.restaurant.security.*; import lombok.RequiredArgsConstructor; import org.springframework.security.authentication.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.Set; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor
public class AuthService {
 private final UserRepository userRepository; private final RoleRepository roleRepository; private final PasswordEncoder passwordEncoder; private final AuthenticationManager authenticationManager; private final JwtService jwtService; private final CurrentUserService currentUserService;
 @Transactional public AuthResponse register(RegisterRequest request){ if(userRepository.existsByEmail(request.getEmail())) throw new BadRequestException("Email already exists"); Role customer=roleRepository.findByRoleName("CUSTOMER").orElseThrow(()->new ResourceNotFoundException("CUSTOMER role not found. Run seed.sql first.")); User user=User.builder().fullName(request.getFullName()).email(request.getEmail()).passwordHash(passwordEncoder.encode(request.getPassword())).phone(request.getPhone()).address(request.getAddress()).status(UserStatus.ACTIVE).roles(Set.of(customer)).build(); user=userRepository.save(user); return toAuthResponse(user); }
 public AuthResponse login(LoginRequest request){ authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.getEmail(), request.getPassword())); User user=userRepository.findByEmail(request.getEmail()).orElseThrow(()->new ResourceNotFoundException("User not found")); return toAuthResponse(user); }
 public UserProfileResponse me(){ return toProfile(currentUserService.getCurrentUser()); }
 private AuthResponse toAuthResponse(User user){ SecurityUser su=new SecurityUser(user); return AuthResponse.builder().token(jwtService.generateToken(su)).userId(user.getUserId()).fullName(user.getFullName()).email(user.getEmail()).roles(roleNames(user)).build(); }
 private UserProfileResponse toProfile(User user){ return UserProfileResponse.builder().userId(user.getUserId()).fullName(user.getFullName()).email(user.getEmail()).phone(user.getPhone()).address(user.getAddress()).status(String.valueOf(user.getStatus())).roles(roleNames(user)).build(); }
 private Set<String> roleNames(User user){ return user.getRoles().stream().map(Role::getRoleName).collect(Collectors.toSet()); }
}
