package com.restaurant.service;
import com.restaurant.dto.cart.*; import com.restaurant.entity.*; import com.restaurant.exception.*; import com.restaurant.model.*; import com.restaurant.repository.*; import com.restaurant.security.CurrentUserService; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal;
@Service @RequiredArgsConstructor
public class CartService {
 private final CartRepository cartRepository; private final CartItemRepository cartItemRepository; private final FoodRepository foodRepository; private final CurrentUserService currentUserService;
 public CartResponse getMyCart(){ return toResponse(getActiveCart(currentUserService.getCurrentUser())); }
 @Transactional public CartResponse add(AddCartItemRequest r){ User user=currentUserService.getCurrentUser(); Cart cart=getActiveCart(user); Food food=foodRepository.findById(r.getFoodId()).orElseThrow(()->new ResourceNotFoundException("Food not found")); if(food.getAvailabilityStatus()!=AvailabilityStatus.AVAILABLE) throw new BadRequestException("Food is not available"); CartItem item=cartItemRepository.findByCart_CartIdAndFood_FoodId(cart.getCartId(), food.getFoodId()).orElse(null); if(item==null){ item=CartItem.builder().cart(cart).food(food).quantity(r.getQuantity()).unitPrice(food.getPrice()).build(); cart.getItems().add(item); } else { item.setQuantity(item.getQuantity()+r.getQuantity()); } cartRepository.save(cart); return toResponse(cartRepository.findById(cart.getCartId()).orElse(cart)); }
 @Transactional public CartResponse update(Long itemId, UpdateCartItemRequest r){ Cart cart=getActiveCart(currentUserService.getCurrentUser()); CartItem item=cartItemRepository.findById(itemId).orElseThrow(()->new ResourceNotFoundException("Cart item not found")); if(!item.getCart().getCartId().equals(cart.getCartId())) throw new ForbiddenException("This cart item does not belong to you"); item.setQuantity(r.getQuantity()); cartItemRepository.save(item); return toResponse(cart); }
 @Transactional public CartResponse remove(Long itemId){ Cart cart=getActiveCart(currentUserService.getCurrentUser()); CartItem item=cartItemRepository.findById(itemId).orElseThrow(()->new ResourceNotFoundException("Cart item not found")); if(!item.getCart().getCartId().equals(cart.getCartId())) throw new ForbiddenException("This cart item does not belong to you"); cart.getItems().remove(item); cartItemRepository.delete(item); return toResponse(cart); }
 @Transactional public void clear(){ Cart cart=getActiveCart(currentUserService.getCurrentUser()); cart.getItems().clear(); cartRepository.save(cart); }
 Cart getActiveCart(User user){ return cartRepository.findByCustomer_UserIdAndCartStatus(user.getUserId(), CartStatus.ACTIVE).orElseGet(()->cartRepository.save(Cart.builder().customer(user).cartStatus(CartStatus.ACTIVE).build())); }
 private CartResponse toResponse(Cart cart){ var items=cart.getItems().stream().map(i->CartItemResponse.builder().cartItemId(i.getCartItemId()).foodId(i.getFood().getFoodId()).foodName(i.getFood().getFoodName()).quantity(i.getQuantity()).unitPrice(i.getUnitPrice()).subtotal(i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity()))).build()).toList(); BigDecimal total=items.stream().map(CartItemResponse::getSubtotal).reduce(BigDecimal.ZERO, BigDecimal::add); return CartResponse.builder().cartId(cart.getCartId()).cartStatus(String.valueOf(cart.getCartStatus())).items(items).totalAmount(total).build(); }
}
