package com.restaurant.service;
import com.restaurant.dto.coupon.*; import com.restaurant.entity.Coupon; import com.restaurant.exception.*; import com.restaurant.model.*; import com.restaurant.repository.CouponRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.LocalDateTime; import java.util.List;
@Service @RequiredArgsConstructor
public class CouponService { private final CouponRepository couponRepository;
 public CouponValidateResponse validate(CouponValidateRequest r){ Coupon c=couponRepository.findByCodeIgnoreCase(r.getCode()).orElse(null); if(c==null) return invalid(r,"Coupon code does not exist"); String reason=invalidReason(c,r.getOrderAmount()); if(reason!=null) return invalid(r,reason); BigDecimal discount=calculateDiscount(c,r.getOrderAmount()); return CouponValidateResponse.builder().couponId(c.getCouponId()).code(c.getCode()).valid(true).discountAmount(discount).finalAmount(r.getOrderAmount().subtract(discount).max(BigDecimal.ZERO)).build(); }
 public BigDecimal calculateDiscount(Coupon c, BigDecimal amount){ BigDecimal discount = c.getDiscountType()==DiscountType.PERCENTAGE ? amount.multiply(c.getDiscountValue()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP) : c.getDiscountValue(); return discount.min(amount); }
 public String invalidReason(Coupon c, BigDecimal amount){ LocalDateTime now=LocalDateTime.now(); if(c.getStatus()!=CouponStatus.ACTIVE) return "Coupon is not active"; if(now.isBefore(c.getStartDate())||now.isAfter(c.getEndDate())) return "Coupon is outside valid date range"; if(amount.compareTo(c.getMinOrderAmount())<0) return "Order does not meet minimum amount"; return null; }
 private CouponValidateResponse invalid(CouponValidateRequest r,String reason){ return CouponValidateResponse.builder().code(r.getCode()).valid(false).reason(reason).discountAmount(BigDecimal.ZERO).finalAmount(r.getOrderAmount()).build(); }
 public List<CouponResponse> list(){ return couponRepository.findAll().stream().map(this::toResponse).toList(); }
 @Transactional public CouponResponse create(CouponRequest r){ if(couponRepository.findByCodeIgnoreCase(r.getCode()).isPresent()) throw new BadRequestException("Coupon code already exists"); Coupon c=Coupon.builder().code(r.getCode().toUpperCase()).discountType(DiscountType.valueOf(r.getDiscountType().toUpperCase())).discountValue(r.getDiscountValue()).minOrderAmount(r.getMinOrderAmount()==null?BigDecimal.ZERO:r.getMinOrderAmount()).startDate(r.getStartDate()).endDate(r.getEndDate()).status(r.getStatus()==null?CouponStatus.ACTIVE:CouponStatus.valueOf(r.getStatus().toUpperCase())).build(); return toResponse(couponRepository.save(c)); }
 @Transactional public CouponResponse status(Long id,String status){ Coupon c=couponRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Coupon not found")); c.setStatus(CouponStatus.valueOf(status.toUpperCase())); return toResponse(couponRepository.save(c)); }
 Coupon findValidByCode(String code, BigDecimal amount){ if(code==null||code.isBlank()) return null; Coupon c=couponRepository.findByCodeIgnoreCase(code).orElseThrow(()->new BadRequestException("Invalid coupon code")); String reason=invalidReason(c, amount); if(reason!=null) throw new BadRequestException(reason); return c; }
 CouponResponse toResponse(Coupon c){ return CouponResponse.builder().couponId(c.getCouponId()).code(c.getCode()).discountType(String.valueOf(c.getDiscountType())).discountValue(c.getDiscountValue()).minOrderAmount(c.getMinOrderAmount()).startDate(c.getStartDate()).endDate(c.getEndDate()).status(String.valueOf(c.getStatus())).build(); }
}
