package com.restaurant.service;
import com.restaurant.dto.order.*; import com.restaurant.entity.*; import com.restaurant.exception.*; import com.restaurant.model.*; import com.restaurant.repository.*; import com.restaurant.security.CurrentUserService; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.List;
@Service @RequiredArgsConstructor
public class OrderService {
 private final OrderRepository orderRepository; private final CartRepository cartRepository; private final CouponService couponService; private final CurrentUserService currentUserService;
 @Transactional public OrderResponse createFromCart(CreateOrderRequest r){ User customer=currentUserService.getCurrentUser(); Cart cart=cartRepository.findByCustomer_UserIdAndCartStatus(customer.getUserId(), CartStatus.ACTIVE).orElseThrow(()->new BadRequestException("Cart is empty")); if(cart.getItems().isEmpty()) throw new BadRequestException("Cart is empty"); BigDecimal subtotal=cart.getItems().stream().map(i->i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity()))).reduce(BigDecimal.ZERO, BigDecimal::add); Coupon coupon=couponService.findValidByCode(r.getCouponCode(), subtotal); BigDecimal discount=coupon==null?BigDecimal.ZERO:couponService.calculateDiscount(coupon, subtotal); OrderType type=parseType(r.getOrderType()); Order order=Order.builder().customer(customer).coupon(coupon).orderType(type).orderStatus(OrderStatus.PENDING_PAYMENT).subtotalAmount(subtotal).discountAmount(discount).totalAmount(subtotal.subtract(discount).max(BigDecimal.ZERO)).note(r.getNote()).build(); cart.getItems().forEach(ci -> order.getItems().add(OrderItem.builder().order(order).food(ci.getFood()).quantity(ci.getQuantity()).unitPrice(ci.getUnitPrice()).itemStatus(OrderItemStatus.PENDING).build())); cart.setCartStatus(CartStatus.CHECKED_OUT); Order saved=orderRepository.save(order); cartRepository.save(cart); return toResponse(saved); }
 public List<OrderResponse> myOrders(){ return orderRepository.findByCustomer_UserIdOrderByCreatedAtDesc(currentUserService.getCurrentUserId()).stream().map(this::toResponse).toList(); }
 public OrderResponse myOrderDetail(Long id){ Order o=getOrder(id); if(!o.getCustomer().getUserId().equals(currentUserService.getCurrentUserId())) throw new ForbiddenException("This order does not belong to you"); return toResponse(o); }
 public List<OrderResponse> adminList(){ return orderRepository.findAll().stream().map(this::toResponse).toList(); }
 public OrderResponse adminDetail(Long id){ return toResponse(getOrder(id)); }
 @Transactional public OrderResponse updateStatus(Long id, String status){ Order o=getOrder(id); o.setOrderStatus(OrderStatus.valueOf(status.toUpperCase())); return toResponse(orderRepository.save(o)); }
 public Order getOrder(Long id){ return orderRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Order not found")); }
 private OrderType parseType(String s){ if(s==null||s.isBlank()) return OrderType.DINE_IN; try{return OrderType.valueOf(s.toUpperCase());}catch(Exception e){throw new BadRequestException("Invalid order type");} }
 public OrderResponse toResponse(Order o){ List<OrderItemResponse> items=o.getItems().stream().map(i->OrderItemResponse.builder().orderItemId(i.getOrderItemId()).foodId(i.getFood().getFoodId()).foodName(i.getFood().getFoodName()).quantity(i.getQuantity()).unitPrice(i.getUnitPrice()).subtotal(i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity()))).itemStatus(String.valueOf(i.getItemStatus())).kitchenNote(i.getKitchenNote()).build()).toList(); return OrderResponse.builder().orderId(o.getOrderId()).customerId(o.getCustomer().getUserId()).customerName(o.getCustomer().getFullName()).staffId(o.getStaff()==null?null:o.getStaff().getUserId()).orderType(String.valueOf(o.getOrderType())).orderStatus(String.valueOf(o.getOrderStatus())).subtotalAmount(o.getSubtotalAmount()).discountAmount(o.getDiscountAmount()).totalAmount(o.getTotalAmount()).couponCode(o.getCoupon()==null?null:o.getCoupon().getCode()).note(o.getNote()).createdAt(o.getCreatedAt()).items(items).build(); }
}
