package com.restaurant.constant;

public enum Permission {
    MENU_READ,
    ORDER_CREATE,
    ORDER_READ_OWN,
    TABLE_MANAGE,
    PAYMENT_CONFIRM,
    KITCHEN_ORDER_READ,
    KITCHEN_STATUS_UPDATE,
    ADMIN_USER_MANAGE,
    ADMIN_MENU_MANAGE,
    ADMIN_COUPON_MANAGE,
    ADMIN_REPORT_READ
}
